### ISSUE TITLE
Admin API types

### ISSUE THREAD

**Issue by tomimaen** [caki0915/shopify-storefront-api-typings#3]
Hey,

Thanks for this library, it's been really useful! 👍 

I noticed that the script in `generateSchema.js` can be used to build the Shopify Admin API types as well, it's otherwise the same but instead of `X-Shopify-Storefront-Access-Token` header, you use `X-Shopify-Access-Token`.

Instead of having to build the Admin API types by hand with this and keeping it in our project repository, I think a separate repository for containing the Admin API types would be neat as well. 

If you are fine with it, I could create one based on the code in this repository (or you can do it as well) 🙂.

Thanks

**Comment by simonhaenisch** [comment]
+1

I was just wondering why `privateMetafield(s)` is missing. Would be nice if this would turn into a `shopify-graphql-api-typings` package instead... but a new `shopify-admin-api-typings` package would do as well 😊

**Comment by caki0915** [comment]
@tomimaen Thanks, that's a great idea :) 
I've created a new package for the Admin API types as well.
https://www.npmjs.com/package/shopify-admin-api-typings
https://github.com/caki0915/shopify-admin-api-typings

@simonhaenisch  I think it's good to stick with 2 different packages since the or are normally not used at the same time and they have types that might conflict with one another. However, for easier maintenance It would be convenient to have both packages in a monorepo.
